### ISSUE TITLE
要是基于wled的就好了

### ISSUE THREAD

**Issue by Lasx** [bszydxh/esp32_study#1]
要是基于wled的就好了。另外问一句，这个需要flash多大容量？

**Comment by bszydxh** [comment]
flash 4M，分区表使用huge_app
以下是编译信息，仅供参考
RAM:   [==        ]  15.3% (used 50296 bytes from 327680 bytes)
Flash: [=====     ]  53.7% (used 1688117 bytes from 3145728 bytes)
